### ISSUE TITLE
Velocity and acceleration of swing foot are represented in incorrect frame

### ISSUE THREAD

**Issue by mmurooka** [jrl-umi3218/lipm_walking_controller#29]
It seems that target velocity and acceleration of `SurfaceTransformTask` for swing foot are passed with represented in incorrect frame in the following:
https://github.com/jrl-umi3218/lipm_walking_controller/blob/b564d655388ae6a6725c504e5c74a62192e58c7c/src/states/SingleSupport.cpp#L151-L152
`SurfaceTransformTask` requires velocity and acceleration represented in the surface frame.

But, it seems these values are represented in world frame.
For example, looking at `xyTakeoffChunk_` of `SwingFoot`, first the start and end positions in the world frame are passed to `RetimedPolynomial<QuinticHermitePolynomial, Eigen::Vector2d>`:
https://github.com/jrl-umi3218/lipm_walking_controller/blob/b564d655388ae6a6725c504e5c74a62192e58c7c/src/SwingFoot.cpp#L61
and then, the interpolated velocity and acceleration are set:
https://github.com/jrl-umi3218/lipm_walking_controller/blob/b564d655388ae6a6725c504e5c74a62192e58c7c/src/SwingFoot.cpp#L133-L134
so they should be represented in world frame.

So far, I haven't encountered any actual problematic behavior related to this issue.

**Comment by stephane-caron** [comment]
Nice catch! :fishing_pole_and_fish: You're absolutely right, the world-to-surface transform is missing :see_no_evil: The linear velocity and acceleration vectors will point in the wrong directions unless the surface frame is aligned with the world frame.

**Comment by mmurooka** [comment]
Thank you for your reply. I made PR: https://github.com/arntanguy/lipm_walking_controller/pull/2. Since I'm currently using the branch of https://github.com/jrl-umi3218/lipm_walking_controller/pull/23, I posted the PR to that branch

**Comment by mmurooka** [comment]
Close this because https://github.com/arntanguy/lipm_walking_controller/pull/2 is merged.
