### ISSUE TITLE
problem building new fork https://github.com/mehdi-benallegue/lipm_walking_controller/tree/rebase_stabilizer_ana

### ISSUE THREAD

**Issue by Aimiliospet** [jrl-umi3218/lipm_walking_controller#43]
Hello @gergondet,
I saw your feedback that the old master branch is not up to date so i tried using the new branch you suggested. However, although i was able to build the old lipm_walking_controller on this new branch i have some problems. As it turns out this branch uses some new solvers of the eigen-lssol class which is as i saw private so i cant get access to it. Moreover it is not included in the repo and can not get it with git clone --recursive. I tried to replace the new include folder with the old one that uses the eigen-quadprog solvers but this created more errors. So is there a way to get access to the eigen-lssos class or do i have to use the old solver and fix the errors? 
Moreover i see that openrtp is also a private repository, but it says "Basically, drcutl's environment setup script and mc_rtc installation script automatically set up most of those libraries." so maybe it is already installed. 
Finally i see that the provided page of the OnlineFootstepPlanner does not exist, but i see that it exists in the repo under plugins so maybe it can work. But these are later problems and firstly i have to overcome the problem of the solver eigen-lssol. 

Thanks in advance!

**Comment by arntanguy** [comment]
My apologies, I hadn't noticed that Tsuru had updated the README on this branch, with details that are not necessarily relevant to your usage. I'll restore it with more relevant instructions ASAP.

In the meanwhile:
- Regarding the footstep planning, you don't need it and can build with `-DONLINE_FOOTSTEP_PLANNER=OFF` (that's the default), so you don't need this dependency.
- Regarding `eigen-lssol`, it is not required, we use https://github.com/jrl-umi3218/eigen-quadprog
- If you need to run in choreonoid environment (dynamic simulation), the easiest is to install it from our mirrors
```sh
# Setup the mirror
curl -1sLf 'https://dl.cloudsmith.io/public/mc-rtc/head/setup.deb.sh' | sudo -E bash
sudo apt install jvrc-choreonoid
```
Then to run
```sh
cd /usr/local/share/hrpsys/samples/JVRC1
choreonoid sim_mc.cnoid
```

**Comment by Aimiliospet** [comment]
@arntanguy 
Thank you for the speedy reply, one thing that comes to mind is that when i do git clone --recursive on the updated branch that was suggested to me [](https://github.com/mehdi-benallegue/lipm_walking_controller/tree/rebase_stabilizer_ana) there is the file Stabilizer.h that uses the eigen-lssol. The older versions of lipm_walking_controller are indeed using the eigen-quadprog which i have installed in my computer. Moreover i can build the old version of lipm_walking_controller [](https://github.com/jrl-umi3218/lipm_walking_controller) but it was suggested that it was rather outdated and i had to use the new one Can i just use the old Stabilizer.h or will this cause further errors? Is there something wrong with the way i'm cloning the repo? 
Thanks in advance!

**Comment by arntanguy** [comment]
There is no `Stabilizer.h` in the new fork, as the stabilizer implementation was moved to `mc_rtc` directly. In the old fork (jrlumi3218@master) there is still the Stabilizer but it is using `eigen-quadprog`. So I'm a bit confused regarding your situation, are you sure you're on the right fork/branch combination?

**For the new fork (recommended)**:

```sh
git clone --recursive git@github.com:mehdi-benallegue/lipm_walking_controller.git
git checkout rebase_stabilizer_ana
```

**For the old fork (not recommended)**:

> Moreover i can build the old version of lipm_walking_controller [old fork](https://github.com/jrl-umi3218/lipm_walking_controller) but it was suggested that it was rather outdated and i had to use the new one

The version on jrl-umi3218@master should work as is (but is missing a few of the latest developements). However, w.r.t your initial issue about `EnabledObservers` the issue was due to an old outdated file that was installed by the previous version of `lipm_walking` but never removed. Thus if you simply remove:
```sh
rm ~/.config/mc_rtc/controllers/LIPMWalking.conf
```
and build the old fork it should work. Please note that this hasn't been used on a real robot for a long while now.

**Comment by Aimiliospet** [comment]
I think there is a problem regarding how i clone the repository. When just now i tried your command i got:
```
git clone --recursive git@github.com:mehdi-benallegue/lipm_walking_controller.git
Cloning into 'lipm_walking_controller'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```
Previously i did `git clone --recursive https://github.com/mehdi-benallegue/lipm_walking_controller.git`
and that's how i also got the Stabilizer file, which indeed doesn't exist in the current github repo.

Can i somehow resolve the access rights problem?
Otherwise i will try with the older repo like you said with removing the file. Thanks in advance!

**Comment by arntanguy** [comment]
You can simply do:
```
git clone --recursive --branch rebase_stabilizer_ana https://github.com/mehdi-benallegue/lipm_walking_controller.git
cd lipm_walking_controller
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
make -j8
sudo make install
```

You were probably on the master branch of this fork instead of the `rebase_stabilizer_ana` branch.

**Comment by Aimiliospet** [comment]
yes seems to be working now, at least for the cloning. I will try to build it now. Thanks for the help!

**Comment by Aimiliospet** [comment]
Hello again Mr. @arntanguy, i indeed managed to build this version of the lipm_walking_controller, but i got back to my issue where i couldnt build the hrpsys-base package which is needed by the mc_openrtm package which installs the interface and the sample of the JVRC1. So i tried the command you mentioned in your first answer:
```
curl -1sLf 'https://dl.cloudsmith.io/public/mc-rtc/head/setup.deb.sh' | sudo -E bash
sudo apt install jvrc-choreonoid
```
but i got following errors: 
```
curl -1sLf 'https://dl.cloudsmith.io/public/mc-rtc/head/setup.deb.sh' | sudo -E bash
Executing the  setup script for the 'mc-rtc/head' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=18.04  codename=bionic  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
  RUN: Importing 'mc-rtc/head' repository GPG key ...gpg: WARNING: unsafe ownership on homedir '/home/aimpet/.gnupg'
   OK: Checking for apt signed-by key support ...
   OK: Importing 'mc-rtc/head' repository GPG key ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'mc-rtc/head' repository via apt ...
 NOPE: Updating apt repository metadata cache ...
Failed to update via apt-get update
Hit:1 http://de.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://ppa.launchpad.net/hrg/daily/ubuntu bionic InRelease
Hit:4 http://de.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:5 http://packages.microsoft.com/repos/code stable InRelease
Ign:6 https://dl.bintray.com/gergondet/multi-contact-head bionic InRelease
Hit:7 http://de.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:8 http://repository.spotify.com stable InRelease
Err:9 https://dl.bintray.com/gergondet/multi-contact-head bionic Release
  Could not handshake: The TLS connection was non-properly terminated. [IP: 3.121.3.67 443]
Hit:10 http://ppa.launchpad.net/neovim-ppa/stable/ubuntu bionic InRelease
Hit:11 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:12 https://packages.microsoft.com/repos/vscode stable InRelease
Hit:13 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu bionic InRelease
Get:14 https://dl.cloudsmith.io/public/mc-rtc/head/deb/ubuntu bionic InRelease [5.183 B]
Hit:15 http://packages.osrfoundation.org/gazebo/ubuntu-stable bionic InRelease
Hit:16 http://packages.ros.org/ros/ubuntu bionic InRelease
Hit:17 https://apt.kitware.com/ubuntu bionic InRelease
Get:18 https://dl.cloudsmith.io/public/mc-rtc/stable/deb/ubuntu bionic InRelease [5.176 B]
Hit:19 http://openrtm.org/pub/Linux/ubuntu bionic InRelease
Reading package lists...
E: The repository 'https://dl.bintray.com/gergondet/multi-contact-head bionic Release' does not have a Release file.
 ^^^^: ... Failed to update via apt-get update - Context above.
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact mc-rtc for further assistance.
 !!!!: 
 !!!!: URL: https://jrl-umi3218.github.io/mc_rtc/
 !!!!: 
```
Since you could answer my previous question, do you maybe know the issue here? 
Why does it say that there is no release file of multi-contact-head ? 

On the other hand, the command **_sudo apt install jvrc-choreonoid_**
was successful and i got the samples for the chorenoid simulation, so maybe i dont need to separately install the hrpsys-base and mc_openrtm. I tried to run it with **_roslaunch mc_rtc_ticker display.launch_**  and **_choreonoid --start-simulation sim_mc.cnoid_** but i got the following error that it can not import the rtm package although i have installed OpenRTM-aist 1.1.2 and it is installed under **_/usr/local/include/openrtm-1.1/rtm_** Is maybe the OpenRTM-aist-Python package also mandatory, because i tried to follow the installation guide and the command 
`wget https://github.com/OpenRTM/OpenRTM-aist-Python/releases/download/svn%252FRELEASE_1_1_2/OpenRTM-aist-Python_1.1.2_ubuntu`lsb_release -rs`_amd64_package.tar.gz`
doesnt work and produces a 404 Not Found error. 
Or is it something that this command **_curl -1sLf 'https://dl.cloudsmith.io/public/mc-rtc/head/setup.deb.sh' | sudo -E bash_** could solve? thats why im asking about this at the start. 

Finally, i thought maybe this is an issue about missing the mc_openrtm, so i tried building it and i got while making a weird error:
```
home/aimpet/devel/src/mc_openrtm/src/MCControl.cpp:116:28: error: ‘const struct mc_rbdyn::RobotModule’ has no member named ‘jointSensors’; did you mean ‘forceSensors’?
   for(const auto & js : rm.jointSensors())
                            ^~~~~~~~~~~~
                            forceSensors
/home/aimpet/devel/src/mc_openrtm/src/MCControl.cpp: In member function ‘virtual RTC::ReturnCode_t MCControl::onExecute(RTC::UniqueId)’:
/home/aimpet/devel/src/mc_openrtm/src/MCControl.cpp:339:85: warning: conversion to ‘_CORBA_ULong {aka unsigned int}’ from ‘__gnu_cxx::__alloc_traits<std::allocator<long unsigned int> >::value_type {aka long unsigned int}’ may alter its value [-Wconversion]
       motorTempIn[m_motorTempNames[i]] = m_motorTempIn.data[m_motorTempToRJOIndex[i]];
                                                                                     ^
/home/aimpet/devel/src/mc_openrtm/src/MCControl.cpp:363:16: error: ‘struct mc_control::MCGlobalController’ has no member named ‘setJointMotorTemperatures’; did you mean ‘setJointTorques’?
     controller.setJointMotorTemperatures(motorTempIn);
                ^~~~~~~~~~~~~~~~~~~~~~~~~
                setJointTorques
```
Is there something wrong with the versions ?

Thanks in advance and sorry about the many questions.

**Comment by Aimiliospet** [comment]
Hello again Mr. @arntanguy, 
i managed to build it and run the `choreonoid sim_mc.cnoid` command successfully, but im having trouble running the controller. How i do it is with four terminals, one for `roscore`, the other for the `choreonoid sim_mc.cnoid` command, the other for displaying the rviz `roslaunch mc_rtc_ticker display.launch` and the last one to run the ticker `rosrun mc_rtc_ticker mc_rtc_ticker` . But when running the ticker with JVRC1 and the LIPMWalking there are some errors that kill the procedure about the versions of LIPMWalking and mc_rtc. Is this the right way to run the controller completely or should i use the other version of lipmwalking ?
Full terminal output by the `rosrun mc_rtc_ticker mc_rtc_ticker` command:
```
tiago-msi@tiagomsi:~/aim_ws/catkin_ws$ rosrun mc_rtc_ticker mc_rtc_ticker 
[info] Loading default global configuration /usr/local/etc/mc_rtc.yaml
[info] Enabled plugins: ROS (autoload)
[info] GUI server enabled
[info] Will serve data on:
[info] - ipc:///tmp/mc_rtc_pub.ipc
[info] - tcp://*:4242
[info] Will handle requests on:
[info] - ipc:///tmp/mc_rtc_rep.ipc
[info] - tcp://*:4343
[info] Loading additional plugin configuration: /usr/local/lib/mc_plugins/etc/ROS.yaml
[error] ExternalFootstepPlannerPlugin was compiled with 1.11.0-3db5cdfec but mc_rtc is currently at version 1.12.0-10107a9e3, you might experience subtle issues and should recompile your code
[info] Loading additional controller configuration: /usr/local/lib/mc_controller/etc/LIPMWalking.yaml
[error] LIPMWalking was compiled with 1.11.0-3db5cdfec but mc_rtc is currently at version 1.12.0-10107a9e3, you might experience subtle issues and should recompile your code
[info] Create controller LIPMWalking
[warning] No calibration file /home/tiago-msi/aim_ws/catkin_data_ws/src/mc_rtc_data/jvrc_description/calib/jvrc1/calib_data.RightFootForceSensor found for force sensor RightFootForceSensor
[warning] No calibration file /home/tiago-msi/aim_ws/catkin_data_ws/src/mc_rtc_data/jvrc_description/calib/jvrc1/calib_data.LeftFootForceSensor found for force sensor LeftFootForceSensor
[warning] No calibration file /home/tiago-msi/aim_ws/catkin_data_ws/src/mc_rtc_data/jvrc_description/calib/jvrc1/calib_data.RightHandForceSensor found for force sensor RightHandForceSensor
[warning] No calibration file /home/tiago-msi/aim_ws/catkin_data_ws/src/mc_rtc_data/jvrc_description/calib/jvrc1/calib_data.LeftHandForceSensor found for force sensor LeftHandForceSensor
[warning] No calibration file /home/tiago-msi/aim_ws/catkin_data_ws/src/mc_rtc_data/jvrc_description/calib/jvrc1/calib_data.RightFootForceSensor found for force sensor RightFootForceSensor
[warning] No calibration file /home/tiago-msi/aim_ws/catkin_data_ws/src/mc_rtc_data/jvrc_description/calib/jvrc1/calib_data.LeftFootForceSensor found for force sensor LeftFootForceSensor
[warning] No calibration file /home/tiago-msi/aim_ws/catkin_data_ws/src/mc_rtc_data/jvrc_description/calib/jvrc1/calib_data.RightHandForceSensor found for force sensor RightHandForceSensor
[warning] No calibration file /home/tiago-msi/aim_ws/catkin_data_ws/src/mc_rtc_data/jvrc_description/calib/jvrc1/calib_data.LeftHandForceSensor found for force sensor LeftHandForceSensor
[info] Robots loaded in controller:
[info] - jvrc1
[info] - ground
[info] MCController(base) ready
[info] Looking for state files in /usr/local/lib/mc_controller/fsm/states/data
[info] Added task FSM_posture_jvrc1
[success] Initialized new ModelPredictiveControl solver
[info] Loading default stabilizer configuration
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```
Thanks in advance!
