### ISSUE TITLE
update link of onlineFootstepPlanner for installation

### ISSUE THREAD

**Issue by Saeed-Mansouri** [jrl-umi3218/lipm_walking_controller#48]
Hello,

It has been mentioned that [https://github.com/isri-aist/OnlineFootstepPlanner](https://github.com/isri-aist/OnlineFootstepPlanner) should be installed, however, this link is no longer available. Would you please update it?

Thanks,

**Comment by gergondet** [comment]
Hi Saeed,

This repository exists but it is private. You can build lipm_walking_controller without it by passing the `-DONLINE_FOOTSTEP_PLANNER=OFF` option to CMake
