### ISSUE TITLE
Stabilizer Issue: Unassigned supportFoot Variable in lipm_walking_controller

### ISSUE THREAD

**Issue by Saeed-Mansouri** [jrl-umi3218/lipm_walking_controller#50]
It appears that a portion of the stabilizer relies on the `supportFoot_` variable. Nevertheless, in the `lipm_walking_controller`, the support foot name has not been assigned to the stabilizer. This oversight is leading to a malfunction in the stabilizer's functionality.

**Comment by gergondet** [comment]
Hi @Saeed-Mansouri 

This was introduced in the stabilizer by https://github.com/jrl-umi3218/mc_rtc/pull/359 (with some follow up changes in  https://github.com/jrl-umi3218/mc_rtc/pull/375)

The member is only used in the `computeCoPonHorizon` method which is called when a reference ZMP horizon is provided to the stabilizer (by calling `horizonReference`)

This feature is not used in `lipm_walking_controller` so not setting the `supportFoot` has no effect here
